version: '3'


services:
  auth:
#    build: './auth'
    image: jboss/keycloak:3.4.3.Final
    deploy:
      replicas: 1
    container_name: auth
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
      - "8443:8443"
#    networks:
#      default:
#        priority: 0
#      keycloak-network:
#        priority: 100
  api:
    build: './api'
    ports:
      - "8081:8080"
    expose:
      - "8080"
      - "443"
    links:
      - auth
      - batch
    deploy:
      replicas: 1
#    networks:
#      - default
#      - frontend
    container_name: api
    depends_on:
      - auth
#  ops:
#    build: './ops'
  batch:
    build: './batch'
    container_name: batch
    links:
      - auth
    ports:
      - "15671:15671"
      - "15672:15672"
    deploy:
      replicas: 1
#    networks:
#      - default
#      - backend
#networks:
#  default:
#  keycloak-network:
#  frontend: