---
- hosts: localhost
  tasks:
    - name: Configure it
      keycloak_client:
        auth_client_id: admin-cli
        admin_url: http://localhost:9990/auth

        auth_keycloak_url: http://localhost:8080/auth
        auth_realm: master
        auth_username: admin
        auth_password: admin
        client_id: test
        enabled: true
        name: test
        realm: master
        state: present
#      delegate_to: keycloak.custom
